theme = "apollo"
taxonomies = [{ name = "tags" }]
# The URL the site will be built for
base_url = "https://nerdtomars.github.io"

title = "Bits and Pixels"
description = "Exploring computer vision, software engineering, and computer graphics through code, research, and random discoveries"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true



# Enable sitemap generation
generate_sitemap = true

# Enable robots.txt generation
generate_robots_txt = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Enable table of contents generation
toc = true

[extra]
# Put all your custom variables here
theme = "toggle"              # light, dark, auto, toggle

# SEO and meta tags
author = "Chongting"
keywords = ["computer vision", "software engineering", "computer graphics", "research", "programming", "technology"]
language = "en"


# Analytics (optional - uncomment and configure if needed)
# [extra.analytics]
# enabled = true
# [extra.analytics.umami]
# website_id = "your-website-id"
# host_url = "https://your-umami-instance.com/"

socials = [
    { name = "github", url = "https://github.com/nerdtomars", icon = "github" },
]

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/tags", url = "/tags", weight = 3 },
]
